{{- if .Values.celeryBeat.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mist-automation.fullname" . }}-celery-beat
  labels:
    {{- include "mist-automation.celery-beat.labels" . | nindent 4 }}
spec:
  replicas: 1  # Beat should always be 1
  selector:
    matchLabels:
      {{- include "mist-automation.celery-beat.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.celeryBeat.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "mist-automation.celery-beat.selectorLabels" . | nindent 8 }}
    spec:
      {{- include "mist-automation.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "mist-automation.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: celery-beat
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.global.imageRegistry }}{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["celery", "-A", "app.core.celery_app", "beat", "--loglevel=info"]
          envFrom:
            - configMapRef:
                name: {{ include "mist-automation.fullname" . }}-config
            - secretRef:
                name: {{ include "mist-automation.secretName" . }}
          env:
            - name: MONGODB_URL
              value: {{ include "mist-automation.mongodbUrl" . }}
            - name: CELERY_BROKER_URL
              value: "{{ include "mist-automation.redisUrl" . }}/1"
            - name: CELERY_RESULT_BACKEND
              value: "{{ include "mist-automation.redisUrl" . }}/2"
            - name: INFLUXDB_URL
              value: {{ include "mist-automation.influxdbUrl" . }}
          resources:
            {{- toYaml .Values.celeryBeat.resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
      {{- with .Values.celeryBeat.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.celeryBeat.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.celeryBeat.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
