{{- if .Values.webhookCollector.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mist-automation.fullname" . }}-webhook-collector
  labels:
    {{- include "mist-automation.webhook-collector.labels" . | nindent 4 }}
  {{- with .Values.webhookCollector.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.webhookCollector.service.type }}
  ports:
    - port: {{ .Values.webhookCollector.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.webhookCollector.service.type "NodePort") .Values.webhookCollector.service.nodePort }}
      nodePort: {{ .Values.webhookCollector.service.nodePort }}
      {{- end }}
  selector:
    {{- include "mist-automation.webhook-collector.selectorLabels" . | nindent 4 }}
{{- end }}
